version: '3'
services:
  mysql:
    image: mysql:5.7.21
    container_name: claw_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=claw_db
      - MYSQL_USER=neptune
      - MYSQL_PASSWORD=1111
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=thwlsWkd23
      - TZ=Asia/Seoul
    volumes:
      - "db-data:/var/lib/mysql"
    ports:
      - 63306:3306
volumes:
  db-data:
